### ISSUE TITLE
Lab2

### ISSUE THREAD

**Issue by zaq007** [1is0/Kondrashov#1]
Use `StringBuilder`
https://github.com/1is0/Kondrashov/blob/35c995599c9ae1c95dbbdafc27610661778be985/Lr2/WorkWithClasses.cs#L17

Please, use meaningful class name
https://github.com/1is0/Kondrashov/blob/35c995599c9ae1c95dbbdafc27610661778be985/Lr2/Funcs.cs#L7
https://github.com/1is0/Kondrashov/blob/35c995599c9ae1c95dbbdafc27610661778be985/Lr2/WorkWithClasses.cs#L5

We have a side-effect here (this change affects all further outputs)
https://github.com/1is0/Kondrashov/blob/35c995599c9ae1c95dbbdafc27610661778be985/Lr2/Funcs.cs#L17

**Comment by AshRaven521** [comment]
Mistakes are fixed according to instructions.
