### ISSUE TITLE
Lr 7

### ISSUE THREAD

**Issue by zaq007** [1is0/Kondrashov#2]
https://github.com/1is0/Kondrashov/blob/877598085ac27d738321990d053bb2907aefa532/Lr7/RationalNumber.cs#L148

Очевидно же, что это неверно в силу врождённой неточности всех вычислений с плавающей точкой.
Вообще, целесообразность таскать за собой rnumber весьма сомнительна для данного класса

Имена `Nint`, `Mnat` неинформативны - непонятно, что из этого числитель, а что - знаменатель

**Comment by AshRaven521** [comment]
Ошибки исправлены согласно инструкциям.
