### ISSUE TITLE
Lab 3,5,6

### ISSUE THREAD

**Issue by zaq007** [1is0/Kondrashov#3]
Пожалуйста, используйте информативные имена классов и интерфейсов (IQualif - плохо)
Specialtys - тоже, это не массив. Обратите внимание, как названы стандартные Enum'ы

IaTPStudent - плохой пример наследования, в том виде, в котором оно реализовано (зачем городить ещё один класс, если я могу просто поменять значение enum'a?)
Плюс, почти все методы, как и сам enum, явно должны быть в классе Student
Или это просто плохое имя класса?

Ваш класс не должен знать ничего об окружении, в котором его используют (какая ему разница?), следовательно, SetParametrs делает очень много лишнего. 

Любой студент - человек без хобби. Это точно так задумано?

**Comment by AshRaven521** [comment]
Ошибки исправлены согласно инструкциям.
